# Generated by Django 4.0.5 on 2022-06-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about',
            field=models.TextField(null=True, verbose_name='Category about'),
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Category image'),
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Category price'),
        ),
    ]
