# Generated by Django 4.0.5 on 2022-06-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='usersname',
            field=models.CharField(max_length=30, null=True, verbose_name='User name'),
        ),
    ]
