# Generated by Django 4.0.5 on 2022-06-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_users_remove_category_usersname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='User image'),
        ),
    ]
