# Generated by Django 4.0.5 on 2022-06-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_img_users_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='imag',
            new_name='img',
        ),
    ]
